### ISSUE TITLE
Simulate delayed voting

### ISSUE THREAD

**Issue by JakeTobak** [ZhangYiJiang/voting-ponies#1]
Find a way to simulate delayed voting action instead of actually delaying voting

**Comment by ZhangYiJiang** [comment]
My current line of thinking is to, as per [Hello71's comment](http://www.reddit.com/r/mylittlepony/comments/1apn36/let_karma_and_discentia_do_the_voting_for_you/c8zq7y6?context=3), capture the original classes on the voting arrows and parent when any arrow is clicked using event capture (such that this happens before `$.fn.vote` and RES' vote capture functions are called), save the classes, then when the event bubbles up again after the inline and RES event handlers are called, save the new classes, replace them with the original classes, then finally after 1.9 seconds (or however long the animation is going to take) replace the old classes with the new one last time. 

I'm not sure if this is worth the trouble though. We could just capture and use eval the event handler after a delay, though I can't seem to get this to work. The eval'd event handler doesn't seem to have the right context.

**Comment by ZhangYiJiang** [comment]
This was fixed with the last update to the script six month ago. Somehow I forgot to close this issue.
